# Generated by Django 3.0 on 2019-12-25 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sudoku",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puzzle", models.CharField(max_length=255)),
                ("box_width", models.PositiveSmallIntegerField()),
                ("box_length", models.PositiveSmallIntegerField()),
                ("rank", models.PositiveSmallIntegerField()),
                ("is_daily", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
