name: Build and Publish Docker

on:
    push:
      tags:
        - '[0-2].[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fdooch/sudoku-solver-back
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
